apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: premnathj/udagram-api-feed:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "750m"                  
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: POSTGRES_USERNAME 
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: POSTGRES_HOST
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: AWS_PROFILE
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: AWS_BUCKET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: JWT_SECRET
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret 